### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by hypery2k** [toolisticon/keycloak-gdpr-module#4]
Basic Performance Tests with Gatlin:

* Encryption/Decrytion (Basic)
* Encryption/Decrytion and auth (Operation Load)

**Comment by hypery2k** [comment]
sample reports are here:

https://www.toolisticon.io/keycloak-gdpr-module/test-reports/gatling/basicsimulation-20210603170041874/
https://www.toolisticon.io/keycloak-gdpr-module/test-reports/gatling/operationalsimulation-20210603171044210/

see report folders here: https://github.com/toolisticon/keycloak-gdpr-module/tree/gh-pages/test-reports/gatling

**Comment by hypery2k** [comment]
The comparison between [normal auth](https://www.toolisticon.io/keycloak-gdpr-module/test-reports/gatling/normalsimulation-20210610042327409/) and [auth+crypt](https://www.toolisticon.io/keycloak-gdpr-module/test-reports/gatling/operationalsimulation-20210610043458469/) is interesting, @mrm1st3r what do you think about that?

**Comment by mrm1st3r** [comment]
Interesting indeed. Handling 95% of de/encryption requests within 50ms looks really good! I guess we don't need to think about time-consumption in that regard.
